/*! \file      events.h
    \version   
    \date      2017-05-25 11:43
    \brief     System events definitions.
    \details   Each system event should be defined here.
    \bug       
    \copyright  
    \author    
*/
/* ------------------------------------------------------------------------------------------------
 *                                     Macros
 * ------------------------------------------------------------------------------------------------
 */
/*! \def     EV_APP_IDLE
    \brief   It is sent when Idle state is detacted.
    
    In events handling loop when no events in app queue is detected the APP_IDLE event is generated by Fwk.
*/
#define EV_APP_IDLE         0x0000

/*! \def     EV_APP_INIT
    \brief   It is sent during system initialization after reset or wakeup.
    
    In events handling loop when no events in app queue is detected the APP_IDLE event is generated by Fwk.
*/
#define EV_APP_INIT         0x0001

/*! \def    EV_APP_SLEEP
    \brief

    <Details>.
*/
#define EV_APP_SLEEP        0x0002

/*! \def    EV_APP_SEC_TICK
    \brief 	Each seconds event making by application framework

    <Details>.
*/
#define EV_APP_SEC_TICK     0x0003

/*! \def    EV_APP_UP
    \brief

    <Details>.
*/
#define EV_APP_UP           0x0004

/*! \def    EV_APP_DOWN
    \brief

    <Details>.
*/
#define EV_APP_DOWN         0x0005

/*! \def    EV_APP_LEFT
    \brief

    <Details>.
*/
#define EV_APP_LEFT         0x0006

/*! \def    EV_APP_RIGHT
    \brief

    <Details>.
*/
#define EV_APP_RIGHT        0x0007

/*! \def    EV_APP_STAR
    \brief

    <Details>.
*/
#define EV_APP_BTN_ACT         0x0008
//#define EV_APP_BTN_PRESSED      0x0009

/*! \def    EV_ADC_SCAN
    \brief

    <Details>.
*/
#define EV_ADC_SCAN      0x000a

/*! \def    EV_SYS_TICK
    \brief  It is a System Tick Event. 

    System Tick Event is generated approximately 10 times. The event is used for some algorithms
    like checking pressed keys where shorter latency is needed.
*/
#define EV_SYS_TICK         0x000b

/*! \def    EV_PARK_ACT
    \brief  App level signal to parking an activity

    <Details>.
*/
#define EV_PARK_ACT         0x000c

/*! \def    EV_DROP_ACT
    \brief  App level signal to cancel activity

    <Details>.
*/
#define EV_DROP_ACT         0x000d

/*! \def    EV_RSM_ACT
    \brief App level signal to Resume activity if possible

    <Details>.
*/
#define EV_RSM_ACT          0x000e

/* ------------------------------------------------------------------------------------------------
 *                                 Type definitions
 * ------------------------------------------------------------------------------------------------
 */
/* ------------------------------------------------------------------------------------------------
 *                                    Functions declarations
 * ------------------------------------------------------------------------------------------------
 */

